INSERT INTO usuario (carnet,nombres,apellidos,contrasena,correo) values 
(202015484, 'Diego', 'Cano','1234','usac@gmail.com');


INSERT INTO catedratico(nombre) values
	('GUEVARA ORELLANA, WILLIAM SAMUEL'),
	('RODAS ROBLEDO, EDGAR FRANCISCO'),
	('ROJAS MORALES, CLAUDIA LICETH'),
	('ESCOBAR LEIVA, OTTO RENE'),
	('ALDANA LARRAZABAL, MIRNA IVONNE'),
	('DÍAZ LÓPEZ, GABRIEL ALEJANDRO'),
	('RAMIREZ RAMIREZ, JURGEN ANDONI'),
	('ESPINO BARRIOS, LUIS FERNANDO'),
	('LONGO MORALES, ALVARO GIOVANNI'),
	('RODRIGUEZ ACOSTA, OTTO AMILCAR'),
	('ARIAS, LUIS ALBERTO'),
	('RALDA RECINOS, ILEANA GUISELA'),
	('MORALES RUIZ, EVELYN CAROLINA'),
	('ORNELIS HOIL, EDGAR RENE'),
	('HERNANDEZ GARCIA, ALVARO OBRAYAN'),
	('BAUTISTA FUENTES, MARIO JOSE'),
	('ESCOBAR ARGUETA, WILLIAM ESTUARDO'),
	('VELASQUEZ OLIVA, MOISES EDUARDO'),
	('VELIZ LINARES, HERMAN IGOR'),
	('CALDERON MENDEZ, NEFTALI DE JESUS'),
	('PÉREZ TÜRK, MARLON ANTONIO'),
	('RUIZ JUAREZ, JOSE MANUEL'),
	('BARRIOS, STANLY'),
	('ZAPETA GÓMEZ, EDWIN ESTUARDO'),
	('PAZ GONZÁLEZ, FERNANDO JOSÉ'),
	('CAMPOS DE LÓPEZ, DAMARIS'),
	('Morales, David Estuardo'),
	('AGUIRRE ORDONEZ, ZULMA KARINA'),
	('TALA AYERDI, VIRGINIA VICTORIA'),
	('AVILA PESQUERA DE MEDINILLA, FLORIZA FELIPA'),
	('DIAZ ARDAVIN , JUAN ALVARO'),
	('PAZ CAMPOS, OSCAR ALEJANDRO'),
	('FERNANDEZ CACERES, CESAR AUGUSTO'),
	('CANCINOS RENDON, MIGUEL ANGEL'),
	('LOPEZ LOPEZ, BAYRON WOSVELY'),
	('SABAN RAXON, EDGAR RUBEN'),
	('CASTILLO REYNA , MANUEL HAROLDO'),
	('Lajpop Ajpacajá, Kevin Adiel'),
	('MENENDEZ PEREZ, GUIPPSY JEANNIRA'),
	('SILVA DE LOS ANGELES, JOSE ANIBAL'),
	('HERNANDEZ RAMIREZ, PEDRO PABLO'),
	('MORATAYA, ALLAN ALBERTO'),
	('LOPEZ FERNANDEZ, MANUEL FERNANDO'),
	('ALTAN SAC , LUDWING FEDERICO'),
	('VETTORAZZI ESPANA, LUIS ALBERTO'),
	('Guzmán Polanco, Jesús Alberto'),
	('MEDINILLA RODRIGUEZ, EVEREST DARWIN'),
	('Aldana Prillwitz, Marco Tulio'),
	('ALVAREZ MEJIA, JORGE LUIS');

INSERT INTO curso (codigo,creditos,nombre,seccion,cat_id) values
	(0283, 6, 'Análisis y Diseño de Sistemas 1','A',1),
	(0283, 6, 'Análisis y Diseño de Sistemas 1','B',2),
	(0785, 7, 'Análisis y Diseño de Sistemas 2','A',3),
	(0785, 7, 'Análisis y Diseño de Sistemas 2','B',5),
	(0778, 5, 'Arquitectura de Computadoras y Ensambladores 1','A',4),
	(0778, 5, 'Arquitectura de Computadoras y Ensambladores 1','B',4),
	(0779, 5, 'Arquitectura de Computadoras y Ensambladores 2','A',6),
	(0779, 5, 'Arquitectura de Computadoras y Ensambladores 2','B',7),
	(0774, 6, 'Bases de Datos 1','B',8),
	(0774, 6, 'Bases de Datos 1','N',9),
	(0775, 7, 'Bases de Datos 2','A',10),
	(0775, 7, 'Bases de Datos 2','B',11),
	(0014, 3, 'Economía','A+',12),
	(0014, 3, 'Economía','A-',13),
	(0772, 6, 'Estructura de Datos','A',14),
	(0772, 6, 'Estructura de Datos','B',15),
	(0772, 6, 'Estructura de Datos','C',8),
	(0787, 6, 'Gerenciales 2','N',16),
	(0787, 6, 'Gerenciales 2','N-',8),
	(0972, 7, 'Inteligencia Artificial 1','A',8),
	(0770, 6, 'Introducción a la Programación y Computación 1','A',6),
	(0770, 6, 'Introducción a la Programación y Computación 1','B',17),
	(0770, 6, 'Introducción a la Programación y Computación 1','C',18),
	(0770, 6, 'Introducción a la Programación y Computación 1','D',19),
	(0770, 6, 'Introducción a la Programación y Computación 1','E',20),
	(0770, 6, 'Introducción a la Programación y Computación 1','F',17),
	(0770, 6, 'Introducción a la Programación y Computación 1','G',2),
	(0771, 6, 'Introducción a la Programación y Computación 2','A',21),
	(0771, 6, 'Introducción a la Programación y Computación 2','B',3),
	(0771, 6, 'Introducción a la Programación y Computación 2','C',22),
	(0771, 6, 'Introducción a la Programación y Computación 2','D',23),
	(0771, 6, 'Introducción a la Programación y Computación 2','N',24),
	(0771, 6, 'Introducción a la Programación y Computación 2','P',25),
	(0796, 4, 'Lenguajes Formales y de Programación','A+',10),
	(0796, 4, 'Lenguajes Formales y de Programación','A-',26),
	(0796, 4, 'Lenguajes Formales y de Programación','B+',27),
	(0796, 4, 'Lenguajes Formales y de Programación','B-',28),
	(0795, 3, 'Logica de Sistemas','A',29),
	(0795, 3, 'Logica de Sistemas','B',30),
	(0795, 3, 'Logica de Sistemas','C',30),
	(0773, 5, 'Manejo e Implementacion de Archivos','A',31),
	(0773, 5, 'Manejo e Implementacion de Archivos','B',17),
	(0773, 5, 'Manejo e Implementacion de Archivos','C',32),
	(0773, 5, 'Manejo e Implementacion de Archivos','D',7),
	(0729, 5, 'Modelación y Simulación 1','A',33),
	(0720, 6, 'Modelación y Simulación 2','A',34),
	(0720, 6, 'Modelación y Simulación 2','B',33),
	(0964, 4, 'Organización Computacional','A',4),
	(0964, 4, 'Organización Computacional','B',4),
	(0964, 4, 'Organización Computacional','C',25),
	(0781, 6, 'Organización de Lenguajes y Compiladores 2','A',35),
	(0781, 6, 'Organización de Lenguajes y Compiladores 2','N',36),
	(0781, 6, 'Organización de Lenguajes y Compiladores 2','B',8),
	(0777, 6, 'Organización Lenguajes y Compiladores 1','B',37),
	(0777, 6, 'Organización Lenguajes y Compiladores 1','C',38),
	(0777, 6, 'Organización Lenguajes y Compiladores 1','N',16),
	(0667, 3, 'Programación Comercial 1','A',39),
	(0667, 3, 'Programación Comercial 1','N',7),
	(0667, 3, 'Programación Comercial 1','P',19),
	(0667, 3, 'Programación Comercial 1','Q',17),
	(0090, 3, 'Programación de Computadoras 1','A',19),
	(0090, 3, 'Programación de Computadoras 1','N',17),
	(0090, 3, 'Programación de Computadoras 1','P',7),
	(0092, 4, 'Programación de Computadoras 2','N',19),
	(0092, 4, 'Programación de Computadoras 2','P',19),
	(0092, 4, 'Programación de Computadoras 2','Q',40),
	(0092, 4, 'Programación de Computadoras 2','R',17),
	(0970, 5, 'Redes de Computadoras 1','A',8),
	(0970, 5, 'Redes de Computadoras 1','N',41),
	(0975, 6, 'Redes de Computadoras 2','N',42),
	(0797, 5, 'Seminario de Sistemas 1','A',43),
	(0797, 5, 'Seminario de Sistemas 1','B',44),
	(0798, 5, 'Seminario de Sistemas 2','A',45),
	(0798, 5, 'Seminario de Sistemas 2','N',25),
	(0281, 6, 'Sistemas Operativos 1','A',46),
	(0285, 4, 'Sistemas Operativos 2','A',14),
	(0786, 5, 'Sistemas Organizaciones y Gerenciales 1','A',25),
	(0786, 5, 'Sistemas Organizaciones y Gerenciales 1','N',24),
	(0780, 8, 'Software Avanzado','A',47),
	(0780, 8, 'Software Avanzado','B',48),
	(0722, 4, 'Teoria de Sistemas 1','A',49),
	(0724, 4, 'Teoria de Sistemas 2','A',49);



SELECT * FROM usuario;
SELECT * FROM catedratico;
SELECT * FROM curso;
/* SELECT * FROM catedratico WHERE nombre = 'ALVAREZ MEJIA, JORGE LUIS'; sirvio para buscar mas rapido en la tabla el codigo de catedratico*/